#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $cfg=read_config();
# We should know what service to run.  This is
# just a safety measure in case it gets run on the wrong host.
my @sl=myservices();

# Fix up config
my $file=$cfg->{'global'}->{deploydir}."/services/shock_service/conf/shock.cfg";
my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];
$mcfg->newval('Address','api-port',$cfg->{services}->{shock}->{'service-port'});

$mcfg->setval('Mongodb','hosts',$cfg->{services}->{shock}->{'mongodb-host'});
$mcfg->newval('Mongodb','database',$cfg->{services}->{shock}->{'mongodb-database'});
$mcfg->newval('Mongodb','user',$cfg->{services}->{shock}->{'mongodb-user'});
$mcfg->newval('Mongodb','password',$cfg->{services}->{shock}->{'mongodb-pwd'});

$mcfg->setval('Paths','site',$cfg->{services}->{shock}->{'site'});
$mcfg->setval('Paths','data',$cfg->{services}->{shock}->{'data'});
$mcfg->setval('Paths','logs',$cfg->{services}->{shock}->{'logs'});

$mcfg->setval('Runtime','GOMAXPROCS',$cfg->{services}->{shock}->{'gomaxprocs'});

$mcfg->WriteConfig($file);

