#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $cfg=read_config();
# We should know what service to run.  This is
# just a safety measure in case it gets run on the wrong host.
my $KB_DEPLOY=$cfg->{'global'}->{deploydir};
my $KB_DC=$cfg->{'global'}->{devcontainer};
my $base_url=$cfg->{global}->{'baseurl'};
$base_url=~s/http.*\/\///;
$base_url=~s/\///;


my @sl=myservices();
my $service=$sl[0];

print "Service: $service\n";

# to do: populate service.cfg file from deployment.cfg
# Fix up config
my $file=$KB_DEPLOY."/services/$service/service.cfg";
my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

# need to populate appropriate stanzas in service.cfg from $cfg
my @keys = qw(
log_syslog
log_file
log_level
awe_service_url
ujs_service_url
workspace_service_url
shock_service_url
handle_service_url
working_directory
plugins_directory
awe_url
ujs_url
clientgroups
);

foreach my $key in @keys
{
	$mcfg->setval($service,$key,$cfg->{services}->{$service}->{$key}) or die "unable to set $key";
}

warn "Updating $file";
$mcfg->WriteConfig($file) or die "Unable to write $file";

# workaround for handle service missing init file
mysystem("touch $KB_DEPLOY/lib/biokbase/AbstractHandle/__init__.py");

