#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $cfg=read_config();
# We should know what service to run.  This is
# just a safety measure in case it gets run on the wrong host.
my @sl=myservices();

# Fix up config
my $file=$cfg->{'global'}->{deploydir}."/services/shock_service/conf/shock.cfg";
my $scfg=$cfg->{services}->{shock};

my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];
$mcfg->newval('Address','api-port',$scfg->{'service-port'});
$mcfg->setval('Admin','email',$scfg->{'admin-email'}) if defined $scfg->{'admin-email'};
$mcfg->newval('Admin','users',$scfg->{'admin-users'}) if defined $scfg->{'admin-users'};

$mcfg->setval('Mongodb','hosts',$scfg->{'mongodb-host'});
$mcfg->newval('Mongodb','database',$scfg->{'mongodb-database'});
$mcfg->newval('Mongodb','user',$scfg->{'mongodb-user'});
$mcfg->newval('Mongodb','password',$scfg->{'mongodb-pwd'});

$mcfg->setval('Paths','site',$scfg->{'site'});
$mcfg->setval('Paths','data',$scfg->{'data'});
$mcfg->setval('Paths','logs',$scfg->{'logs'});

$mcfg->setval('Runtime','GOMAXPROCS',$scfg->{services}->{shock}->{'gomaxprocs'});

$mcfg->WriteConfig($file);

