#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;
use Config::IniFiles;

exit if $ARGV[0] eq 'bootstrap';

my $hashfile;
$hashfile=shift @ARGV if ($ARGV[0] ne '-f' && $ARGV[0] ne '-b');
exit if $ARGV[0] eq 'bootstrap';

my $cfg=read_config();

my $acfg=$cfg->{services}->{awe};

symlink "/mnt/awe/site","/var/www/awe_service" unless -e "/var/www/awe_service";

my $file=$cfg->{'global'}->{deploydir}."/services/awe_service/conf/awe.cfg";
fix_config($file,$acfg);

fix_configjs("/mnt/awe/site/js/config.js");

# TODO: Create client groups


sub fix_config {
  my $file=shift;
  my $acfg=shift;
# Fix up config

  my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

# Update Mongo Params
  $mcfg->setval('Mongodb','hosts',$acfg->{'mongodb-host'});
  $mcfg->newval('Mongodb','database',$acfg->{'mongodb-database'});
  $mcfg->newval('Mongodb','user',$acfg->{'mongodb-user'});
  $mcfg->newval('Mongodb','password',$acfg->{'mongodb-pwd'});

#Update Ports
  $mcfg->setval('Ports','site-port',$acfg->{'site-port'});
  $mcfg->setval('Ports','api-port',$acfg->{'service-port'});
  $mcfg->setval('Admin','email','scanon@lbl.gov');
# Reuse mongo password
  $mcfg->setval('Admin','secretkey',$acfg->{'mongodb-pwd'});
  $mcfg->setval('Admin','users',$acfg->{'admin-user'});

# Update urls
  $mcfg->setval('External','site-url',$acfg->{'site-url'});
  $mcfg->setval('External','api-url',$acfg->{'api-url'});


# Adjust some settings
  for my $param ('read','write','create-user'){
    $mcfg->setval('Anonymous',$param,'false');
  }
  for my $param ('delete','cg_read','cg_write','cg_delete'){
    $mcfg->newval('Anonymous',$param,'false');
  }
  $mcfg->WriteConfig($file);

}

sub fix_configjs {
  my $js=shift;
# Fix up config.js in the site area
#
  mysystem("/bin/cp $js $js.orig");
  open(JSO, "$js.orig") or die "Unable to open $js.orig";
  open(JSN, "> $js");
  while(<JSO>){
    my $apiurl=$acfg->{'api-url'};
    #s/:7080/$apiurl/;
    s/ ":/ "$apiurl/;
    print JSN;
  }
}
