#!/bin/sh

# Install Maria

if [ $(mysql -V|grep -c Maria) -ne 1 ] ; then
  apt-get -y install python-software-properties
  apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'

  apt-get -y update
  apt-get -y install mariadb-server
fi

# Install XFS
if [ $(grep -c /data /proc/mounts) -lt 1 ] ; then
  apt-get -y install xfsprogs
  mkfs -t xfs /dev/vdb
  mkdir /data
  mount /dev/vdb /data
fi
