#!/usr/bin/env perl 

# TODO: Change things to run as non-root

use lib '../perl';
use KBDeploy;
use strict;

my $cfg=read_config("../cluster.ini",'global');


my $me=`hostname`;
chomp $me;


my @sl=myservices($me);

mkdocs(@sl);
exit if -e '/kb/deployment';

stop_service(@sl);

deploy_service(@sl);

start_service(@sl);
