#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

exit if $ARGV[0] eq 'bootstrap';
exit if -e '/kb/deployment' && $ARGV[0] ne '-f';

my $cfg=read_config("$FindBin::Bin/../cluster.ini",'global');
my @sl=('awe_service','workspace_deluxe','uploader','idserver');

my $LOGFILE="/tmp/deploy.log";
my $KB_DEPLOY=$cfg->{'global'}->{deploydir};
my $KB_DC=$cfg->{'global'}->{devcontainer};

if ( -e "$KB_DEPLOY/services/awe_service/stop_service"){
  mysystem(". $KB_DEPLOY/user-env.sh;$KB_DEPLOY/services/awe_service/stop_aweclient | echo Ignore");
}

deploy_service('',@sl);
chdir($KB_DC.'/modules');
opendir(my $dh, './') || die "can't opendir ./: $!";
my @modules = grep { ! /^\./ && -d "./$_" } readdir($dh);
closedir $dh;

for my $_ (@modules){
    print "$_\n";
    next if /auth_service/;
    next if /kb_model_seed/;
    chdir("$KB_DC/modules/$_");
    my $target='deploy-client';
    $target='deploy' if (/auth/);
    mysystem(". $KB_DC/user-env.sh;make $target >> $LOGFILE 2>&1");
}

chdir($KB_DC.'/modules/awe_service') or die "Unable to change dir";
mysystem(". $KB_DC/user-env.sh;make deploy-awe-client > $LOGFILE 2>&1");

my $file=$KB_DEPLOY."/services/awe_service/conf/awec.cfg";

# Fix up config
my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

$mcfg->newval('Client','group',$cfg->{services}->{aweworker}->{'group'}) or die "Unable to set group";
$mcfg->newval('Client','clientgroup_token',$cfg->{services}->{aweworker}->{'token'}) or die "Unable to set token";
$mcfg->setval('Client','serverurl',$cfg->{services}->{aweworker}->{'serverurl'}) or die "Unable to set serverurl";
$mcfg->setval('Client','supported_apps','*');

$mcfg->WriteConfig($file) or die "Unable to write $file";

mysystem(". $KB_DEPLOY/user-env.sh;$KB_DEPLOY/services/awe_service/start_aweclient");


# TODO
#
# export AUTH='Authorization: OAuth $TOK
#
#curl -X POST -H "$AUTH" http://next-awe:7107/cgroup/next
#
# Grab output and stuff in config
