#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

exit if $ARGV[0] eq 'bootstrap';

my $cfg=read_config("$FindBin::Bin/../cluster.ini",'global');

my $me=`hostname`;
chomp $me;

exit if -e '/kb/deployment' && $ARGV[0] ne '-f';

my @sl=myservices($me);

stop_service(@sl);

deploy_service(@sl);

my $file=$cfg->{'global'}->{deploydir}."/services/shock_service/conf/shock.cfg";

# Fix up config

my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

$mcfg->setval('Mongodb','hosts',$cfg->{services}->{shock}->{'mongodb-host'});
$mcfg->newval('Mongodb','database',$cfg->{services}->{shock}->{'mongodb-database'});
$mcfg->newval('Mongodb','user',$cfg->{services}->{shock}->{'mongodb-user'});
$mcfg->newval('Mongodb','password',$cfg->{services}->{shock}->{'mongodb-pwd'});

mysystem("cp shock.cfg ".$cfg->{'global'}->{deploydir}."/servies/shock_service");

start_service(@sl);
