#!/usr/bin/env perl 

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;
use Config::IniFiles;

my $cfg=read_config("$FindBin::Bin/../cluster.ini",'global');


my $me=`hostname`;
chomp $me;

my @sl=myservices($me);

stop_service(@sl);

deploy_service(@sl);

my $file=$cfg->{'global'}->{deploydir}."/services/awe_service/conf/awe.cfg";

symlink "/mnt/awe/site","/var/www/awe_service" unless -e "/var/www/awe_service";
# Fix up config

my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

$mcfg->setval('Mongodb','hosts',$cfg->{services}->{awe}->{'mongodb-host'});
$mcfg->newval('Mongodb','database',$cfg->{services}->{awe}->{'mongodb-database'});
$mcfg->newval('Mongodb','user',$cfg->{services}->{awe}->{'mongodb-user'});
$mcfg->newval('Mongodb','password',$cfg->{services}->{awe}->{'mongodb-pwd'});
$mcfg->setval('Ports','api-port',$cfg->{services}->{awe}->{'port'});
$mcfg->setval('Admin','email','scanon@lbl.gov');
# Reuse mongo password
$mcfg->setval('Admin','secretkey',$cfg->{services}->{awe}->{'mongodb-pwd'});

$mcfg->setval('External','site-url',$cfg->{services}->{awe}->{'site-url'});
$mcfg->setval('External','api-url',$cfg->{services}->{awe}->{'api-url'});


# Adjust some settings
for my $param ('read','write','create-user'){
  $mcfg->setval('Anonymous',$param,'false');
}
for my $param ('delete','cg_read','cg_write','cg_delete'){
  $mcfg->newval('Anonymous',$param,'false');
}
$mcfg->WriteConfig($file);

my $js="/mnt/awe/site/js/config.js";
mysystem("/bin/cp $js $js.orig");
open(JSO, "$js.orig") or die "Unable to open $js.orig";
open(JSN, "> $js");
while(<JSO>){
  #s/:7080/$cfg->{services}->{awe}->{'api-url'}/;
  s/ ":/ "$cfg->{services}->{awe}->{'api-url'}/;
  print JSN;
}
#    "workflow_ip": ":7080/awf",
#

start_service(@sl);
