#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $cfg=read_config("$FindBin::Bin/../cluster.ini",'global');
# We should know what service to run.  This is
# just a safety measure in case it gets run on the wrong host.
my @sl=myservices();
exit unless scalar(@sl);

my $hashfile;
$hashfile=shift @ARGV if ($ARGV[0] ne '-f' && $ARGV[0] ne '-b');

exit if $ARGV[0] eq 'bootstrap';
exit if -e '/kb/deployment' && $ARGV[0] ne '-f';

my @list=split /,/,$cfg->{services}->{aweworker}->{'deploy'};

my $LOGFILE="/tmp/deploy.log";
my $KB_DEPLOY=$cfg->{'global'}->{deploydir};
my $KB_DC=$cfg->{'global'}->{devcontainer};
my $MAKE_OPTIONS=$cfg->{'global'}->{'make-options'};

if ( -e "$KB_DEPLOY/services/awe_service/stop_service"){
  mysystem(". $KB_DEPLOY/user-env.sh;$KB_DEPLOY/services/awe_service/stop_aweclient | echo Ignore");
}

deploy_service('',@list);
chdir($KB_DC.'/modules');
opendir(my $dh, './') || die "can't opendir ./: $!";
my @modules = grep { ! /^\./ && -d "./$_" } readdir($dh);
closedir $dh;

for my $_ (@modules){
    print "$_\n";
    next if /kb_model_seed/;
    chdir("$KB_DC/modules/$_");
    my $target='deploy';
    mysystem(". $KB_DC/user-env.sh;make $target $MAKE_OPTIONS>> $LOGFILE 2>&1");
}


# Fix up config
my $file=$KB_DEPLOY."/services/awe_service/conf/awec.cfg";
my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

$mcfg->newval('Client','group',$cfg->{services}->{aweworker}->{'group'}) or die "Unable to set group";
$mcfg->newval('Client','clientgroup_token',$cfg->{services}->{aweworker}->{'token'}) or die "Unable to set token";
$mcfg->setval('Client','serverurl',$cfg->{services}->{aweworker}->{'serverurl'}) or die "Unable to set serverurl";
$mcfg->setval('Client','supported_apps','*');

$mcfg->WriteConfig($file) or die "Unable to write $file";

mysystem(". $KB_DEPLOY/user-env.sh;$KB_DEPLOY/services/awe_service/start_aweclient");


# TODO
#
# export AUTH='Authorization: OAuth $TOK
#
#curl -X POST -H "$AUTH" http://next-awe:7107/cgroup/next
#
# Grab output and stuff in config
