#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $hashfile;

$hashfile=shift @ARGV if ($ARGV[0] ne '-f' && $ARGV[0] ne '-b');
exit if $ARGV[0] eq 'bootstrap';

exit if (KBDeploy::is_complete('invocation') && $ARGV[0] ne '-f');

my $cfg=read_config();
my $MAKE_OPTIONS=$cfg->{global}->{'make-options'};

my $LOGFILE="/tmp/deploy.log";
my $KB_DC=$cfg->{'global'}->{devcontainer};

stop_service('invocation');

my @sl=('Workspace','invocation','cdmi_api', 'translation', 'CompressionBasedDistance', 'protein_info_service', 'trees', 'fbaModelServices', 'probabilistic_annotation', 'genome_annotation', 'genotype_phenotype_api', 'idserver', 'handle_service', 'ontology_service', 'plant_expression_service','kmer_annotation_figfam', 'meme', 'networks','CoExpression', 'KBaseExpression');

#m5nr
#uploader
#search

my $ad=$KB_DC."/autodeploy.cfg";
KBDeploy::generate_autodeploy($ad);
print "Running auto deploy\n";
chdir $KB_DC;
mysystem(". $KB_DC/user-env.sh;perl auto-deploy $ad >> $LOGFILE 2>&1");

start_service('invocation');

start_service('invocation');
KBDeploy::mark_complete(@sl);
