#!/usr/bin/env perl

# TODO: Change things to run as non-root

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use Getopt::Std;
use strict;

my %opt;
my $force=0;
my $dryrun=0;
my $bootstrap=0;

getopts('nfb',\%opt);
$dryrun=1 if defined $opt{n};
$bootstrap=1 if defined $opt{b};
$force=1 if defined $opt{f};

my $hashfile=shift @ARGV;
exit if $bootstrap;

my $cfg=read_config();

my @sl=myservices();
exit unless scalar(@sl);

mkdocs(@sl);
exit if (! defined $hashfile && KBDeploy::is_complete(@sl) && $force);
#
# redploy_service will tell us if we need to repeploy but
# it also populates that hashes to deploy
my $redeploy=KBDeploy::redeploy_service("../$hashfile",@sl);
if (! $redeploy){
  print " - No deploy required for $sl[0]\n";
  exit;
}

if ($dryrun){
  print " - Redploy needed.  Exiting with dryrun\n";
  exit;
}

stop_service(@sl);

KBDeploy::auto_deploy(@sl);

KBDeploy::postprocess(@sl);

#stop_service(@sl);
start_service(@sl);

KBDeploy::mark_complete(@sl);
