#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/../perl/";
use KBDeploy;
use strict;

my $cfg=read_config("$FindBin::Bin/../cluster.ini",'global');


mkdir "/kb" unless -e "/kb";

if ($ARGV[0] eq 'bootstrap' ){
  bootstrap();
  exit;
}

mkdir "/kb/dev" unless -e "/kb/dev";
mkdir "/kb/deployment" unless -e "/kb/deployment";
chdir "/kb/dev";
KBDeploy::clonetag('narrative') unless -e "/kb/dev/narrative";
KBDeploy::clonetag('ui-common') unless -e "/kb/dev/ui-common";

# Move this to bootstrap section?
mysystem("yes|/bin/sh narrative/docker/lua-dependencies.txt") unless -e "/usr/local/lib/lua";


chdir "/kb/dev/ui-common";
mysystem("./deployFunctionalSite.sh > /dev/null");

# TODO:  Remove refernces to next.  Get it from config file
# TODO:  abstract out this recursive grep and sed into a perl function
#
# Replace kbase.us/serices with new url
mysystem('grep -rl //kbase.us/services /kb/deployment/ui-common 2>/dev/null|xargs sed -i "s/\/\/kbase.us\/services/\/\/next.kbase.us\/services/g" ');

# Samething for www.kbase.us
mysystem('grep -rl //www.kbase.us/services /kb/deployment/ui-common 2>/dev/null|xargs sed -i "s/\/\/www.kbase.us\/services/\/\/next.kbase.us\/services/g" ');

# Now for the search url
mysystem('grep -rl  dev07.berkeley.kbase.us/search /kb/deployment/ui-common 2>/dev/null|xargs sed -i "s/dev07.berkeley.kbase.us/next.kbase.us\/services/"');

# Now for the narrative url
mysystem('grep -rl narrative.kbase.us /kb/deployment/ui-common 2>/dev/null|xargs sed -i "s/narrative.kbase.us/next04.berkeley.kbase.us/"');


sub bootstrap {
  if ( ! -e "/usr/bin/pip") {
    mysystem("apt-get update");
    mysystem("apt-get -y install python-pip");
  }

  chdir "/kb" or die "Unable to chdir";
  KBDeploy::clonetag('bootstrap') unless -e "/kb/bootstrap";

  mysystem("apt-get install -y libcurl4-gnutls-dev") unless -e "/usr/bin/curl-config";
  mysystem("apt-get install -y python-dev ncurses-dev") unless -e "/usr/include/ncurses.h";
  #mysystem("pip install -r bootstrap/kb_python_runtime/python-pip-list-narrative");


  mysystem("apt-get install -y python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose") unless -e "/usr/bin/ipython";


  mysystem("apt-get -y install python-software-properties") unless -e "/usr/bin/add-apt-repository";
  if ( ! -e "/usr/sbin/nginx" ){
    mysystem("echo ''|add-apt-repository ppa:nginx/stable");
    mysystem("apt-get update ; apt-get install -y nginx");
  }

  if ( ! -e "/usr/bin/lua5.1" ){
    mysystem("apt-get install lua5.1");
    mysystem("apt-get install luarocks");
    mysystem("apt-get install liblua5.1-0");
    mysystem("apt-get install liblua5.1-0-dev");
    mysystem("apt-get install liblua5.1-json");
    mysystem("apt-get install liblua5.1-lpeg2");
    mysystem("luarocks install luasocket");
    mysystem("luarocks install luajson");
    mysystem("luarocks install penlight");
    mysystem("luarocks install lua-spore");
    mysystem("luarocks install luacrypto");
  }

}
