#!/bin/sh

SDIR=/root/dt/${1}

mkdir $SDIR
rsync -avz ${1}:dt $SDIR/
diff -ru ./config $SDIR/dt/config
diff -ru ./perl $SDIR/dt/perl
diff -ru ./cluster.ini $SDIR/dt/cluster.ini
diff -ru ./deploy_cluster $SDIR/dt/deploy_cluster
