#!/bin/sh

HTTPS_PORT=6443
HTTP_PORT=6080
IMAGE=kbase/depl:1.0
WWW=$(docker-compose ps|grep _www_|awk '{print $1}')

docker run --name narrative \
	--link $WWW:www \
	-d \
	--env MYSERVICES=narrative \
	-p 0.0.0.0:${HTTP_PORT}:80 \
	-p 0.0.0.0:${HTTPS_PORT}:443 \
	-v /var/run/docker.sock:/var/run/docker.sock \
	$IMAGE
